version: 0.1
env:
   secrets-manager:
    TOKEN: mainToken1:tokenforsonar
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=projectKey -Dsonar.organization=projectOrg -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=TOKEN
