version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=newawscodebuildproject -Dsonar.organization=newawscodebuildproject -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=1c2b929f6789698a0ecbd07aa3842dd29b39e3a9
