version: 0.2

env:
  secrets-manager:
    TOKEN: mainToken:tokenforsonar
    
phases:
  install:
    runtime-versions:
      nodejs: 18

    commands:
      - yarn install

  pre_build:

    commands:

      - apt-get update

      - apt-get install -y jq

      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip

      - echo "Current path is >>>"

      - sh $pwd

      - unzip ./sonar-scanner-cli-4.7.0.2747-linux.zip

      - ls $pwd

      - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/

      - sonar-scanner -Dsonar.login=$TOKEN -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=engr-mayz -Dsonar.organization=engr-mayz

      - sleep 5

      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=prembly >result.json

      - cat result.json

      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi

      - |-
        apt-get update
        apt-get -y install wget
        apt-get -y install default-jdk
        wget https://github.com/zaproxy/zaproxy/releases/download/v2.13.0/ZAP_2.13.0_Linux.tar.gz
        tar -xvf ZAP_2.13.0_Linux.tar.gz
        cd ZAP_2.13.0
        ./zap.sh -cmd -quickurl https://prembly.com -quickprogress -quickout ../zap_report.html
  
        
    commands:
      - yarn run build
      - aws s3 sync build/ s3://admin-portal-cloudfront


  post_build:
    commands:
      - aws configure set preview.cloudfront true
      - aws cloudfront create-invalidation --distribution-id E2UCWTDKQDOES3 --paths "/*"

artifacts:
  files: '**/*'
  base-directory: build
